### ISSUE TITLE
Zero Defense Creature Cards

### ISSUE THREAD

**Issue by 7jeronimo7** [kotc-game/kotc#1]
In playing with some people at Origins, several questions came up, one was regarding creating a creature with an offensive power of 1, a resource cost of 1, and a defensive power of 0.  That configuration of a creature appears to be possible.  Would a creature such as this be able to do battle?  I think someone referred to this as a "Ratling Deck" if an entire deck could be stacked with such a creature.  We ruled it a valid configuration and I believed the "rats" won or nearly won the game.

**Comment by onpon4** [comment]
Yes, such a creature can do battle (and yes, it's a possible configuration, with a resource cost of 1). If it gets hit at all, it is destroyed (because getting hit by an attack triggers the check for destruction). I'd actually like to have some example cards with these stats, and I think that will be in set 5 for the 2nd edition release ("future" branch if you're curious).

So how did it go at Origins overall?

**Comment by 7jeronimo7** [comment]
Origins was great; I spent the majority of my time, about 5 to 7 hours each night in the “Werewolf/Deception” room, playing mostly Secret Hitler.  I did try out several other deception games that I had never played before and had fun.  Only played 1 game of Werewolf though; was out on a mercy kill in the opening round so that I could jump in on an open spot at Secret Hitler – lucky to have gotten out as it took 2 hours to kill 3 people in that Werewolf game and for some reason they placed no time limits on the game.

Only got in a single game of Battlestar Galactica; lost as a “Cylon Leader” along with the other cylons but did complete all 4 of my cylon leader objectives. First time playing as a cylon leader for me.

I do have a few more mini pages of notes/comments regarding kotc; I think I misplaced one of the pages; hopefully it turns up.  Mostly the comments are random and somewhat unorganized.  I can start a new issue/thread and place them all into one to be sorted out later if you would like.  In terms of improvements, probably the most helpful thing would be to have some mechanism to indicate the timing of when a spell can be played.  I was thinking changing the background color of the card (like Dominion); someone else had suggested changing the icons on the bottom of the card from the purple triangles to something else to indicate at a glance if they are reactionary, etc.  That would probably be the easier and better suggestion to implement.

**Comment by onpon4** [comment]
Hm, the problem with that is it's not just spells that can be reactionary, creature abilities can be too. And spells can be designed to react to several different kinds of things.

Of course, it's perfectly allowable to change the look of the card, so just adding a colored background would not go against the rules at all, and neither would changing the triangles to something else. Was this a suggestion to help see more quickly what spells need to be played as traps? If so, it seems customizations like that should do the trick.

**Comment by 7jeronimo7** [comment]
Yes, it was for quickly identifying how and when a card can be placed without having to re-read the first sentence repeatedly.

**Comment by onpon4** [comment]
Ah, I see, you mean the part where cards with activation conditions can't be cast from the hand.

In any case, I have an idea: I could add an optional monochrome watermark-like image behind the ability text if it includes an activation condition, kind of like what Duel Masters has to indicate civilization to colorblind people. The nice thing about this idea is it wouldn't confuse players as to what kind of card it is, and it could be used with creatures to boot. In fact, I could make this a "play restriction" icon (maybe a lock symbol?) that can double for use with the new "caveat" system I'm adding for the 2nd edition rules (which can include special conditions for summoning creatures). That's probably a nice idea.

**Comment by onpon4** [comment]
So, I've implemented that idea I mentioned in the comment above. These "reactionary" cards (that is, any spell with an activation condition) now have a padlock shadow-icon under the card text. Creatures with the new summoning requirements have this icon, too, so in effect it's a "play restriction" icon.

Of course, you still have to read to see what creature abilities have activation conditions, but this is inevitable anyway because a creature can have any number of abilities.

**Comment by onpon4** [comment]
And I should probably close this issue. xD
