### ISSUE TITLE
Question: Duration of effects (Bloodborne Transmission)

### ISSUE THREAD

**Issue by 7jeronimo7** [kotc-game/kotc#2]
While playing **Bloodborne Transmission**, there was a question as to whether the effect was for the current turn or permanent for the effected creature(s).  We had another play-tester rule that its effect should be for a single turn only due to the relatively low cost of the card.

Another comment on the card was that it should be reactionary in response to an attack, but that was only one person's opinion.  I would think if someone wants its effects to be reactionary that they could customize their own version of the card and adjust the cost accordingly.

**Comment by onpon4** [comment]
This should be all set. I added a paragraph elaborating on what it means for all stats to be reset.
