### ISSUE TITLE
Card Suggestion - Quick Reference Card for Turn Order

### ISSUE THREAD

**Issue by 7jeronimo7** [kotc-game/kotc#3]
For newbies and when teaching the game, it would be very helpful to have a card that lists out the 4 phases of each turn as a quick reference.  I would have made my own, but I ran out of time.

**Comment by onpon4** [comment]
Whew! So, I did you one better: I made a set of four "tip cards", with the turn order card being one of them. These cards compact the basic rules into the simplest possible terms I could manage.
