### ISSUE TITLE
Review and Add Felis Catus

### ISSUE THREAD

**Issue by 7jeronimo7** [kotc-game/kotc#5]
Attached is the PNG image.  I will have to email you separately the .xcf file as apparently it is an unsupported file type.

![felis_catus](https://user-images.githubusercontent.com/40149623/42066710-17d3ee7e-7b10-11e8-8a56-2482a835cf19.png)

**Comment by onpon4** [comment]
By the way, as far as attaching files goes, you should be able to compress the .xcf into a zip file. That would work. Or you could email it to me, that works too.

**Comment by 7jeronimo7** [comment]
I'll update the card either tonight or tomorrow morning and re-attach as a zip if I can.

**Comment by 7jeronimo7** [comment]
[FelisCatus.zip](https://github.com/kotc-game/kotc/files/2151232/FelisCatus.zip)

Hopefully I got it right this time; if not, let me know...

**Comment by onpon4** [comment]
Perfect! I've added it in, with just one minor alteration (the addition of the "This card has no abilities" text, which is optional, but I prefer to use it.

I'm going to try to fill that page up with some more cards. I've already started with one other creature. Either way, I'm going to plan on releasing the expansion pack by Monday.
