### ISSUE TITLE
Similarity to arcmage

### ISSUE THREAD

**Issue by alexgleason** [kotc-game/kotc#6]
Hi, this isn't a bug, I just wanted to point out that another libre card game exists: http://arcmage.org/

It's fundamentally different in the sense that the cards all have arbitrary abilities. I've considered creating a libre alternative to MTG myself and have been faced with the same question, so I'm glad to see both approaches being taken.

Anyway I just wanted to run this by you in case you haven't seen it before. It has lots of free art you could use too, including the card frames.

**Comment by onpon4** [comment]
I know. As said on kotc-game.github.io, I took some inspiration from it. It does look like a very nice and well-made game, though I haven't had a chance to properly play it yet.

**Comment by onpon4** [comment]
As regards using Arcmage's art, I'm interested in doing that, but I don't know where to get copies of the art alone (as opposed to full Arcmage cards).

**Comment by alexgleason** [comment]
The best place is through the git repo: https://github.com/wtactics/art

There's some effort happening to make this more readily available on the website, but it hasn't been finished yet.

**Comment by onpon4** [comment]
Ah, I never saw that repo. Thanks for the link!
